BUGFIX: `@styleguide.container` doesnt get `content` prop
sitegeist/Sitegeist.Monocle pull request #164
Opened 2022-03-05 09:27 UTC by mhsdesign

As shown here https://github.com/sitegeist/Sitegeist.Monocle#preview-containers
the container should automatically get the `content` prop. This is not working because

1. 'element' need to be in the custom renderPath and the path must be relative,
2. 'element.container' wont work as we need to override deeper ('element' would only be the current prototype component)

demo:
https://fusionpen.punkt.de/fusionpen/c3d9af2b6c532ef03c904b8bf711ef3bb405f36e.html

2022-04-22 16:43 UTC, mficzel approved these changes

2022-04-22 16:52 UTC, mficzel requested changes
For me this leads to an error 

```
An exception was thrown while Neos tried to render your page
Path Part element<Vendor not well-formed

/
 <Sitegeist.Monocle:Preview.Page>/
  body<Neos.Fusion:Join>/
   preview/
    __meta/
     process/
      applyContainer<Neos.Fusion:Case>/
       hasStyleguideContainer<Neos.Fusion:Matcher>/
        renderer<Neos.Fusion:Renderer>/

2022-04-22 16:52 UTC, mficzel commented
I alway built my containers in a way that i can use them as processor 
```
prototype(Vendor.Site:Container) < prototype(Neos.Fusion:Component) {
    content = ${value}
    renderer = afx`
        <div>fooo{props.content}bar</div>
    `
}
```
I wonder wether a better description would help.

2022-04-22 18:38 UTC, mhsdesign commented
as you described above this will surely work - but the example suggests that `content = null` would also work (eg. That the content prop is set magically)

2022-04-22 18:56 UTC, mficzel commented
I agree that the documentation is misleading.

2022-04-23 08:35 UTC, mhsdesign commented
If it's meant to use 'value' directly, then line 90 is superfluous `element.content = ${value}` - but I assumed it should be auto set...

2022-04-23 11:08 UTC, mficzel commented
I would like it to work but probably was mislead into thinking so by my style of creating containers.

2022-04-24 08:18 UTC, mhsdesign commented on Resources/Private/Fusion/Prototypes/Preview/Page.fusion
>                          renderPath = ${'/<' + prototypeName + '>/__meta/styleguide/container'}
```suggestion
                        renderPath = ${'element<' + prototypeName + '>/__meta/styleguide/container'}
```

2022-04-24 08:19 UTC, mhsdesign commented
> For me this leads to an error
> 
> ```
> An exception was thrown while Neos tried to render your page
> Path Part element<Vendor not well-formed
> 
> /
>  <Sitegeist.Monocle:Preview.Page>/
>   body<Neos.Fusion:Join>/
>    preview/
>     __meta/
>      process/
>       applyContainer<Neos.Fusion:Case>/
>        hasStyleguideContainer<Neos.Fusion:Matcher>/
>         renderer<Neos.Fusion:Renderer>/
> ```

I just dont get why it throws, will try it out locally some time

2022-10-24 15:26 UTC, mficzel commented
@mhsdesign do you see a way to solve this or is this "fixed by adjusting the documentation" here https://github.com/sitegeist/Sitegeist.Monocle#preview-containers

2022-10-25 17:45 UTC, mhsdesign commented
yes thats fine by me - i would also find it weird to prefill the `content` prop with `value`

2022-10-25 17:45 UTC, closed without merging

2022-10-25 17:47 UTC, mhsdesign commented
noice you also cleaned up the non working fusion with https://github.com/sitegeist/Sitegeist.Monocle/commit/0599c0b4b67bda2975506d3efc26905adc3789f4 

1A mit sahne